### ISSUE TITLE
Primitives

### ISSUE THREAD

**Issue by jgordinier** [dillonkearns/elm-decoder-koans#1]
Going thought the first primitives and getting this error. 
https://imgur.com/4ehstAM
Do not use expect.equal with floats. 

Not sure if this is intended to work this way. If so I will continue to work on it.

**Comment by jgordinier** [comment]
![Screen Shot 2020-06-22 at 2 29 23 PM](https://user-images.githubusercontent.com/1313581/85327571-d29ebf80-b494-11ea-8e8f-71d363ce8e28.png)

This is what I have so far.

**Comment by dillonkearns** [comment]
You're right, thank you for reporting the issue! It looks like Elm 0.19 complains when you do Expect.equal with a float now because the best practice is to test floats within a threshold to make sure expectations are predictable.

Should be fixed now! Sorry for the slow turnaround, should be all good now!
